### ISSUE TITLE
What is the mapping of the semantic map of person image to the merged K=8 attribute?

### ISSUE THREAD

**Issue by nitthilan** [menyifang/ADGAN#10]
I am trying to map the segmentation mask output with the merged (K=8) indexes. The current indexes I have are 

np.array(('Background',  # always index 0
                        'Hat', 'Hair', 'Glove', 'Sunglasses',
                        'UpperClothes', 'Dress', 'Coat', 'Socks',
                        'Pants', 'Jumpsuits', 'Scarf', 'Skirt',
                        'Face', 'Left-arm', 'Right-arm', 'Left-leg',
                        'Right-leg', 'Left-shoe', 'Right-shoe',))
is the input

and the merged index is : 
background, hair, face, upper clothes, pants, skirt, arm and leg

Is there a code you could share where this operation is performed? 
I am trying to reuse the pre-trained model

**Comment by menyifang** [comment]
Hi @nitthilan, our segmentation files 'semantic_merge3' is obtained with the following merge manner:
0(Background): Background
1(Pants): Pants
2(Hair): Hat, Hair
3(Skirt): Skirt
4(Face): Face, Sunglasses, Jumpsuits
5(UpperClothes): UpperClothes, Dress, Coat, Scarf
6(Arm): Glove, Left-arm, Right-arm
7(Leg): Socks, Left-leg, Right-leg, Left-shoe, Right-shoe

**Comment by genghisun** [comment]
> Hi @nitthilan, our segmentation files 'semantic_merge3' is obtained with the following merge manner:
> 0(Background): Background
> 1(Pants): Pants
> 2(Hair): Hat, Hair
> 3(Skirt): Skirt
> 4(Face): Face, Sunglasses, ** **Jumpsuits** **
> 5(UpperClothes): UpperClothes, Dress, Coat, Scarf
> 6(Arm): Glove, Left-arm, Right-arm
> 7(Leg): Socks, Left-leg, Right-leg, Left-shoe, Right-shoe

Hi, Can you explain why Jumpsuits are merged in the Face class?
