### ISSUE TITLE
About the perceptual loss

### ISSUE THREAD

**Issue by mazzzystar** [menyifang/ADGAN#3]
In your paper, the perceptual loss was:
```python
# vggsubmod refers to certain layer of VGG.
Lper = L1(gram(vggsubmod(x)), gram(vggsubmod(y))  
```
However in your implementation:
https://github.com/menyifang/ADGAN/blob/d948cb135801c83295e9427cab5d7d738436aa95/losses/L1_plus_perceptualLoss.py#L63-L72

Could you give some explanation on that ? thanks.

**Comment by menyifang** [comment]
> In your paper, the perceptual loss was:
> 
> ```python
> # vggsubmod refers to certain layer of VGG.
> Lper = L1(gram(vggsubmod(x)), gram(vggsubmod(y))  
> ```
> 
> However in your implementation:
> https://github.com/menyifang/ADGAN/blob/d948cb135801c83295e9427cab5d7d738436aa95/losses/L1_plus_perceptualLoss.py#L63-L72
> 
> Could you give some explanation on that ? thanks.

Hi @mazzzystar, thank you for your correction! Here we directly use the implement of perceptual loss from [PATN](https://github.com/tengteng95/Pose-Transfer) and mistake it as common style loss in [perceptual loss](https://arxiv.org/pdf/1603.08155.pdf). We will correct this issue in our arxiv version.
