### ISSUE TITLE
Not able to reproduce the result

### ISSUE THREAD

**Issue by nitthilan** [menyifang/ADGAN#9]
I am not able to reproduce the results using the pre-trained models. 
![fashionWOMENJackets_Coatsid0000417103_1front jpg___fashionWOMENJackets_Coatsid0000417103_2side jpg_vis](https://user-images.githubusercontent.com/4926564/86510020-34b6c900-bda1-11ea-9a7c-f55120454b2a.jpg)

The above is the output I am getting. Can you predict why I am getting this issue?

**Comment by nitthilan** [comment]
The problem is already addressed

**Comment by genghisun** [comment]
Hi @nitthilan, when i inference on 8570 test pairs using the pre-trained model, I got almost the same result as you (see below), could you share how you solved this problem? Thanks~

![image](https://user-images.githubusercontent.com/26201304/89619991-88956000-d8c1-11ea-9fcb-b2a4742c2a52.jpeg)
![image](https://user-images.githubusercontent.com/26201304/89620266-0194b780-d8c2-11ea-9f58-d40e228d35f1.jpeg)

**Comment by nitthilan** [comment]
It is addressed in this issue: https://github.com/menyifang/ADGAN/issues/6

It was due to the number of GPUS. Use 2 GPUs using the pre-trained model.
